// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Xq3cynzJ3c_bZr4GXfFKaqI5UFWLj1c',
    appId: '1:757870279920:android:71e0b2250811ed1089d635',
    messagingSenderId: '757870279920',
    projectId: 'employeefirebase-88886',
    storageBucket: 'employeefirebase-88886.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCezeMze_6W8anbZKyXmr21LVm-qnfS0E',
    appId: '1:757870279920:web:503f57a0251d298e89d635',
    messagingSenderId: '757870279920',
    projectId: 'employeefirebase-88886',
    authDomain: 'employeefirebase-88886.firebaseapp.com',
    storageBucket: 'employeefirebase-88886.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMb7mxZkcFwpctrqQYcNpW6YORvlLFZeU',
    appId: '1:757870279920:ios:e606e2d80ce9190989d635',
    messagingSenderId: '757870279920',
    projectId: 'employeefirebase-88886',
    storageBucket: 'employeefirebase-88886.firebasestorage.app',
    iosBundleId: 'com.example.employeeFirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMb7mxZkcFwpctrqQYcNpW6YORvlLFZeU',
    appId: '1:757870279920:ios:e606e2d80ce9190989d635',
    messagingSenderId: '757870279920',
    projectId: 'employeefirebase-88886',
    storageBucket: 'employeefirebase-88886.firebasestorage.app',
    iosBundleId: 'com.example.employeeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCezeMze_6W8anbZKyXmr21LVm-qnfS0E',
    appId: '1:757870279920:web:ce83a7aea087985d89d635',
    messagingSenderId: '757870279920',
    projectId: 'employeefirebase-88886',
    authDomain: 'employeefirebase-88886.firebaseapp.com',
    storageBucket: 'employeefirebase-88886.firebasestorage.app',
  );

}